### ISSUE TITLE
Components and Dynamic zones not being populated

### ISSUE THREAD

**Issue by TNortnern** [Barelydead/strapi-plugin-populate-deep#11]
Plugin does not populate relational content nested inside a component or dynamic zone e.g.

Mycomponent -> `title, description, category(one to one category)`

Using https://market.strapi.io/plugins/strapi-plugin-populate-deep

Only populates `title, description` but never populates the `category` field

**Comment by TNortnern** [comment]
Nvm, realized that populations require the role to access to the populated fields in v4

**Comment by vlowe85** [comment]
> Nvm, realized that populations require the role to access to the populated fields in v4

ahh, thanks, that was my issue too :D
