### ISSUE TITLE
Population of deep content structures using slug

### ISSUE THREAD

**Issue by thushara318** [Barelydead/strapi-plugin-populate-deep#14]
Required System information

Node.js version: v14.15.4
NPM version: 6.14.16
Strapi version: 4.2.0
Database: Postgres : 8.6.0
Operating system: ubuntu 18.10

**Population of deep content structures using slug.Any examples?**

http://localhost:1337/api/articles/128?populate=deep,2 , works perfectly 

 http://localhost:1337/api/articles/new-slug?populate=deep,10, when id is replaced with slug it is not working as expected.

**Comment by smellydelli** [comment]
You can use:

http://localhost:1337/api/articles?filters[Slug][$eq]=new-slug&populate=deep,10

**Comment by thushara318** [comment]
@smellydelli Thank you , it works wonderfully.
