### ISSUE TITLE
node engine

### ISSUE THREAD

**Issue by XanderD99** [Barelydead/strapi-plugin-populate-deep#23]
I am currently updating my strapi project to use node v18, but I am getting an unsupported engine warning when running `npm install`. Is it a hard failure or can this be upgraded to also support up to node v18?

**Comment by Barelydead** [comment]
I don't think it is  a hard limit. I'll look in to testing it and making a new release when I get the chance

**Comment by thomcrielaard** [comment]
Node v18 support would be appreciated :)

**Comment by coolsoftwaretyler** [comment]
Also jumping in to let y'all know I'd love to use node 18.

**Comment by coolsoftwaretyler** [comment]
If y'all need this in the meantime, I just posted https://www.npmjs.com/package/strapi-plugin-populate-deep-no-engine-constraints

I don't intend to actually maintain it, but I need it tonight, so maybe others will want it. It'll basically be locked on the current plugin version, I forked from `main`.
